[package]
name = "redis-rs"
version = "0.1.0"
authors = ["Andre Sa de Mello <asmello@pm.me>"]
edition = "2021"

[dependencies]
anyhow = "1.0.59"
async-recursion = "1.0.4"
bytes = "1.3.0"
thiserror = "1.0.32"
tokio = { version = "1.23.0", features = ["full"] }
